// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8N21arOI3FWLopGQL8WYIByDzCdAuq0',
    appId: '1:76490898448:android:ed3df7662d74f90a10de95',
    messagingSenderId: '76490898448',
    projectId: 'mini-project-1-persistence',
    storageBucket: 'mini-project-1-persistence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhi7VHqXu2JoG7mFdJMjFqQYjl3p2FbE',
    appId: '1:76490898448:ios:ad05de2729ff480910de95',
    messagingSenderId: '76490898448',
    projectId: 'mini-project-1-persistence',
    storageBucket: 'mini-project-1-persistence.appspot.com',
    iosClientId: '76490898448-ugvr0pqictbi0v561bo9nvba55g6nrnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
